### ISSUE TITLE
Please re-write this whole file

### ISSUE THREAD

**Issue by clayboone** [clayboone/scripts#4]
https://github.com/clayboone/scripts/blob/1a1466b16795b3a1b3f0026071d70d3681f79660/get_public_ip.py#L1

All of it. kthxbye

**Comment by Chewyslice** [comment]
What

**Comment by clayboone** [comment]
Ha! Sorry, I selected the first line of the file, meaning "the whole file is ugly and in need of a re-write." The very first line is okay.

**Comment by Chewyslice** [comment]
Lol wondered why I got an email about it

**Comment by clayboone** [comment]
I re-wrote it.
